### ISSUE TITLE
Example for BluRay UDF ISOs?

### ISSUE THREAD

**Issue by myron0815** [stephenc/java-iso-tools#16]
Example BD used: http://download.blender.org/durian/movies/
Any ideas what will be needed to support a BD VolumeDescriptor?

```
java.lang.RuntimeException: com.github.stephenc.javaisotools.loopfs.api.LoopFileSystemException: Invalid block size: 0
    at com.github.stephenc.javaisotools.loopfs.spi.AbstractBlockFileSystem.iterator(AbstractBlockFileSystem.java:63)
[...]
Caused by: com.github.stephenc.javaisotools.loopfs.api.LoopFileSystemException: Invalid block size: 0
    at com.github.stephenc.javaisotools.loopfs.iso9660.Iso9660VolumeDescriptorSet.validateBlockSize(Iso9660VolumeDescriptorSet.java:210)
    at com.github.stephenc.javaisotools.loopfs.iso9660.Iso9660VolumeDescriptorSet.deserializePrimary(Iso9660VolumeDescriptorSet.java:128)
    at com.github.stephenc.javaisotools.loopfs.iso9660.Iso9660VolumeDescriptorSet.deserialize(Iso9660VolumeDescriptorSet.java:99)
    at com.github.stephenc.javaisotools.loopfs.spi.AbstractBlockFileSystem.loadVolumeDescriptors(AbstractBlockFileSystem.java:78)
    at com.github.stephenc.javaisotools.loopfs.spi.AbstractBlockFileSystem.iterator(AbstractBlockFileSystem.java:61)
```

**Comment by myron0815** [comment]
silly me - BD is UDF.
udf-impl seems not to be implemented, now checking with sabre.
Can anyone point me how to easily iterate over the filesystem?
Was quite easy with the iso-9660 impl... but i failed with UDF... (only writer methods?)
